SELECT persona.apellido1, persona.apellido2, persona.nombre FROM persona WHERE tipo = 'alumno' ORDER BY persona.apellido1, persona.apellido2, persona.nombre;
SELECT CONCAT(persona.nombre,' ',persona.apellido1, ' ',persona.apellido2) AS 'Nombre completo' FROM persona WHERE tipo = 'alumno' AND telefono IS NULL ORDER BY nombre;
SELECT CONCAT(persona.nombre,' ',persona.apellido1, ' ',persona.apellido2) AS 'Nombre completo' FROM persona WHERE tipo = 'alumno' AND YEAR(CAST(fecha_nacimiento AS DATE)) = 1999;
SELECT CONCAT(persona.nombre,' ',persona.apellido1, ' ',persona.apellido2) AS 'Nombre completo' FROM persona WHERE tipo = 'profesor' AND telefono IS NULL ORDER BY nombre AND RIGHT(nif, 1) = 'K';
SELECT asignatura.nombre AS 'Nombre Asignatura' FROM asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7;
SELECT persona.apellido1, persona.apellido2, persona.nombre, departamento.nombre AS 'Nombre Departamento' FROM persona JOIN profesor ON persona.id = profesor.id_profesor JOIN departamento ON profesor.id_departamento = departamento.id WHERE persona.tipo = 'profesor' ORDER BY persona.apellido1, persona.apellido2, persona.nombre;
SELECT asignatura.nombre AS 'Nombre Asignatura' FROM asignatura JOIN alumno_se_matricula_asignatura ON asignatura.id = alumno_se_matricula_asignatura.id_asignatura JOIN curso_escolar ON alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id JOIN persona ON alumno_se_matricula_asignatura.id_alumno = persona.id WHERE persona.nif = '26902806M';
SELECT DISTINCT departamento.nombre FROM departamento JOIN profesor ON departamento.id = profesor.id_departamento JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor JOIN grado ON asignatura.id_grado = grado.id WHERE grado.nombre = 'Grado en Ingeniería Informática (Plan 2015)';
SELECT DISTINCT CONCAT(persona.nombre,' ',persona.apellido1, ' ',persona.apellido2) AS 'Nombre completo' FROM persona JOIN alumno_se_matricula_asignatura ON persona.id = alumno_se_matricula_asignatura.id_alumno JOIN curso_escolar ON alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id WHERE curso_escolar.anyo_inicio <= 2018 AND curso_escolar.anyo_fin >= 2019;
SELECT CONCAT(persona.nombre,' ',persona.apellido1, ' ',persona.apellido2) AS 'Nombre completo', departamento.nombre AS 'Nombre Departamento' FROM persona LEFT JOIN profesor ON persona.id = profesor.id_profesor LEFT JOIN departamento ON profesor.id_departamento = departamento.id;
SELECT departamento.nombre AS 'Nombre Departamento', persona.apellido1, persona.apellido2, persona.nombre FROM departamento LEFT JOIN profesor ON departamento.id = profesor.id_departamento LEFT JOIN persona ON profesor.id_profesor = persona.id ORDER BY departamento.nombre, persona.apellido1, persona.apellido2;
SELECT CONCAT(persona.nombre,' ',persona.apellido1, ' ',persona.apellido2) AS 'Nombre completo' FROM persona LEFT JOIN profesor ON persona.id = profesor.id_profesor LEFT JOIN departamento ON profesor.id_departamento = departamento.id WHERE departamento.nombre IS NULL;
SELECT departamento.nombre AS 'Nombre Departamento' FROM departamento LEFT JOIN profesor ON departamento.id = profesor.id_departamento LEFT JOIN persona ON profesor.id_profesor = persona.id WHERE persona.nombre IS NULL;
SELECT CONCAT(persona.nombre,' ',persona.apellido1, ' ',persona.apellido2) AS 'Nombre completo' FROM persona LEFT JOIN profesor ON persona.id = profesor.id_profesor LEFT JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor WHERE persona.tipo = 'profesor' AND asignatura.id_profesor IS NULL;
SELECT asignatura.nombre AS 'Nombre Asignatura' FROM asignatura WHERE asignatura.id_profesor IS NULL;
SELECT DISTINCT departamento.nombre AS 'Nombre Departamente' FROM departamento LEFT JOIN profesor ON departamento.id = profesor.id_departamento LEFT JOIN asignatura ON profesor.id_profesor = asignatura.id_profesor WHERE asignatura.id_profesor IS NULL; 
SELECT COUNT(persona.id) AS 'Total Alumnos' FROM persona WHERE persona.tipo = 'alumno';
SELECT COUNT(persona.id) AS 'Total Alumnos nacidos 1999' FROM persona WHERE persona.tipo = 'alumno' AND YEAR(CAST(fecha_nacimiento AS DATE)) = 1999 ;
SELECT departamento.nombre AS 'Nombre Departamento', COUNT(profesor.id_profesor) AS 'Número de Profesores' FROM departamento LEFT JOIN profesor ON departamento.id = profesor.id_departamento GROUP BY departamento.nombre;
SELECT departamento.nombre AS 'Nombre Departamento', COUNT(profesor.id_profesor) AS 'Número de Profesores' FROM departamento JOIN profesor ON departamento.id = profesor.id_departamento GROUP BY departamento.nombre ORDER BY COUNT(profesor.id_profesor) DESC;
SELECT departamento.nombre AS 'Nombre Departamento', COUNT(profesor.id_profesor) AS 'Número de Profesores' FROM departamento LEFT JOIN profesor ON departamento.id = profesor.id_departamento GROUP BY departamento.nombre;
SELECT grado.nombre AS 'Nombre Grado', COUNT(asignatura.id) AS 'Numero de Asignaturas' FROM grado LEFT JOIN asignatura ON grado.id = asignatura.id_grado GROUP BY grado.nombre ORDER BY COUNT(asignatura.id) DESC;
SELECT grado.nombre AS 'Nombre Grado', COUNT(asignatura.id) AS 'Numero de Asignaturas' FROM grado LEFT JOIN asignatura ON grado.id = asignatura.id_grado GROUP BY grado.nombre HAVING COUNT(asignatura.id) > 40 ORDER BY COUNT(asignatura.id) DESC;


